version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://admin:admin12345@ezquizzdb.bbat3.mongodb.net/?retryWrites=true&w=majority&appName=ezQuizzDB
      - NODE_ENV=production
    volumes:
      - ./public/uploads:/app/public/uploads
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
